# Permalinks
permalink:           pretty

# Setup
title:               fd.py
tagline:             ">>> from stuff import faisal"
url:
paginate:            1
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              faisal dosani
  url:               https://www.instagram.com/robotoprime/
  email:             faisal (dot) dosani (at) gmail.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/poole/poole

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-mentions


pages_list:
  About: '/about'
  Data-Barista: '/data-barista'
  Publications: '/publications'
